# Generated by Django 5.2 on 2025-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='outputs/processed'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/'),
        ),
    ]
